/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.product.store.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.product.store.model.Apply;
import com.liferay.product.store.service.ApplyLocalServiceUtil;

/**
 * The extended model base implementation for the Apply service. Represents a row in the &quot;CUX_Apply&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplyImpl}.
 * </p>
 *
 * @author zhangpengfei
 * @see ApplyImpl
 * @see com.liferay.product.store.model.Apply
 * @generated
 */
public abstract class ApplyBaseImpl extends ApplyModelImpl implements Apply {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a apply model instance should use the {@link Apply} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ApplyLocalServiceUtil.addApply(this);
		}
		else {
			ApplyLocalServiceUtil.updateApply(this);
		}
	}
}